Importing the dependencies

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import  train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [10]:
hd = pd.read_csv("C:\Dev\ml-projects\heart-disease-prediction\heart_disease_data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\boluv\AppData\Local\Temp\ipykernel_18360\21753926.py:1: SyntaxWarning: invalid escape sequence '\D'
  hd = pd.read_csv("C:\Dev\ml-projects\heart-disease-prediction\heart_disease_data.csv")

In [11]:
hd.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [12]:
hd.shape

(303, 14)

In [13]:
hd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [14]:
hd.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [15]:
hd['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [16]:
hd.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [17]:
# Splitting the feautures into target variable
x = hd.drop(columns='target', axis=1)
y = hd['target']

In [29]:
print (y.shape)

(303,)

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state=4, stratify = y)

In [20]:
print(x_test)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
292   58    0   0       170   225    1        0      146      1      2.8
38    65    0   2       155   269    0        1      148      0      0.8
26    59    1   2       150   212    1        1      157      0      1.6
286   59    1   3       134   204    0        1      162      0      0.8
267   49    1   2       118   149    0        0      126      0      0.8
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
271   61    1   3       134   234    0        1      145      0      2.6
280   42    1   0       136   315    0        1      125      1      1.8
186   60    1   0       130   253    0        1      144      1      1.4
274   47    1   0       110   275    0        0      118      1      1.0
168   63    1   0       130   254    0        0      147      0      1.4

     slope  ca  thal
292      1   2     1
38       2   0     2
26       2   0     2
286      2   2     2
267      2   3     2
..     ...  ..   ...
271      1   2     2
280      1   0     1
186      2   1     3
274      1   1     2
168      1   1     3

[61 rows x 13 columns]

In [21]:
print( x.shape, x_test.shape,x_train.shape)

(303, 13) (61, 13) (242, 13)

In [22]:
print(y.shape,y_train.shape,y_test.shape)

(303,) (242,) (61,)

In [23]:
# Model training
Lr = LogisticRegression()

In [24]:
Lr.fit(x_train, y_train)

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [25]:
# accuracy on training data
x_train_prediction = Lr.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [26]:
print(training_data_accuracy)

0.8264462809917356

In [27]:
x_test_pred = Lr.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_pred, y_test)

In [28]:
print("The testing data accuracy was: ",testing_data_accuracy )

The testing data accuracy was:  0.8852459016393442