In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
f = pd.read_csv('/content/flood.csv')

In [ ]:
f.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475

In [ ]:
f.describe()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000
mean,4.991480,4.984100,5.01594,5.008480,4.989060,4.988340,5.01536,4.988600,5.006120,5.006380,...,5.006060,4.999920,4.984220,4.97982,4.988200,4.984980,5.00512,4.994360,4.990520,0.499660
std,2.236834,2.246488,2.23131,2.222743,2.243159,2.226761,2.24500,2.232642,2.234588,2.241633,...,2.238107,2.247101,2.227741,2.23219,2.231134,2.238279,2.23176,2.230011,2.246075,0.050034
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.285000
25%,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.00000,3.000000,3.000000,3.00000,3.000000,3.000000,0.465000
50%,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.00000,5.000000,5.000000,0.500000
75%,6.000000,6.000000,6.00000,6.000000,6.000000,6.000000,6.00000,6.000000,6.000000,6.000000,...,6.000000,6.000000,6.000000,6.00000,6.000000,6.000000,6.00000,6.000000,6.000000,0.535000
max,16.000000,18.000000,16.00000,17.000000,17.000000,17.000000,16.00000,16.000000,16.000000,18.000000,...,17.000000,17.000000,16.000000,16.00000,17.000000,19.000000,22.00000,16.000000,16.000000,0.725000

In [ ]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   MonsoonIntensity                 50000 non-null  int64
 1   TopographyDrainage               50000 non-null  int64
 2   RiverManagement                  50000 non-null  int64
 3   Deforestation                    50000 non-null  int64
 4   Urbanization                     50000 non-null  int64
 5   ClimateChange                    50000 non-null  int64
 6   DamsQuality                      50000 non-null  int64
 7   Siltation                        50000 non-null  int64
 8   AgriculturalPractices            50000 non-null  int64
 9   Encroachments                    50000 non-null  int64
 10  IneffectiveDisasterPreparedness  50000 non-null  int64
 11  DrainageSystems                  50000 non-null  int64
 12  CoastalVulnerability             50000 non-null  int64
 13  Landslides                       50000 non-null  int64
 14  Watersheds                       50000 non-null  int64
 15  DeterioratingInfrastructure      50000 non-null  int64
 16  PopulationScore                  50000 non-null  int64
 17  WetlandLoss                      50000 non-null  int64
 18  InadequatePlanning               50000 non-null  int64
 19  PoliticalFactors                 50000 non-null  int64
 20  FloodProbability                 50000 non-null  float64
dtypes: float64(1), int64(20)
memory usage: 8.0 MB

In [ ]:
# Turning the flood coloums into
f['Flood'] = (f['FloodProbability'] > 0.5).astype(int)
print(f['Flood'].value_counts())

Flood
0    26505
1    23495
Name: count, dtype: int64

In [ ]:
f.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability,Flood
0,3,8,6,6,4,4,6,2,3,2,...,7,4,2,3,4,3,2,6,0.450,0
1,8,4,5,7,7,9,1,5,5,4,...,2,6,2,1,1,9,1,3,0.475,0
2,3,10,4,1,7,5,4,7,4,9,...,4,4,8,6,1,8,3,6,0.515,1
3,4,4,2,7,3,4,1,4,6,4,...,2,6,6,8,8,6,6,10,0.520,1
4,3,7,5,2,5,8,5,2,7,5,...,6,5,3,3,4,4,3,4,0.475,0

In [ ]:
x = f.drop(columns=['Flood', 'FloodProbability'], axis=1)
y = f['Flood']

In [ ]:
# Splitting into target variables
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=43)

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(40000, 20) (10000, 20) (40000,) (10000,)

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print()
print(classification_report(y_test, y_pred))

Accuracy: 0.9019

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      5221
           1       0.94      0.85      0.89      4779

    accuracy                           0.90     10000
   macro avg       0.91      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000